### ISSUE TITLE
Casos quedan con estado en borrador

### ISSUE THREAD

**Issue by alejosar99** [tomolimo/processmaker-community#1]
Hola @tomolimo , ayuda.. me pasa que completo una tarea y el caso queda con status de borrador pero en realidad debe estar con status completado

**Comment by tomolimo** [comment]
Hello @alejosar99 
You MUST post in English (or French) 😃 
Thank you,
Regards,
Tomolimo

**Comment by tomolimo** [comment]
Hello @alejosar99 
As there is no answer to my last post, I close this issue.
And anyway if you need support for the community edition, please go to the forum and post here: https://forum.processmaker.com/
Thank you,
Regards,
Tomolimo
